# Configuration file for libinput-gestures.
# Mark Blakeney, Sep 2015
#
# The default configuration file exists at /etc/libinput-gestures.conf.
#
# Each gesture line has 3 [or 4] arguments separated by whitespace:
# action motion [finger_count] command
#
# where action and motion may be:
#   swipe <up, down, left, right, left_up, left_down, right_up, right_down>
#   pinch <in, out, clockwise, anticlockwise>
#   hold on
###############################################################################

# Move to next/prev workspace (_internal requires wmctrl)
gesture swipe left  _internal ws_left
gesture swipe right _internal ws_right

# Minimize/restore windows
gesture swipe down xdotool key super+Page_Down
gesture swipe up   xdotool key super+shift+Page_Down

# See windows
gesture swipe up 4 rofi -show window

