# Proper colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Customize UI
# set -g status off
set -g status-position top
set -g status-left "#S> "
set -g status-right ""

# Better responsiveness
set -s escape-time 0

# Easier prefix (Ctrl+a instead of Ctrl+b)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Make tmux feel like "real tabs"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

# Re-style current window/tab
set -g automatic-rename on
setw -g window-status-current-format "[#I:#W]"
setw -g window-status-current-style bold

# Normal "tab" (window) controls (with Alt)
bind -n M-t new-window
bind -n C-PageUp previous-window
bind -n C-PageDown next-window

# Direct tab switching with Alt+#
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Direct pane splitting (s and v instead of % and ")
bind -n M-s split-window -h
bind -n M-v split-window -v

# Pane navigation with Alt + vim keys
bind -nr M-j select-pane -D
bind -nr M-k select-pane -U
bind -nr M-h select-pane -L
bind -nr M-l select-pane -R

